services:
  - type: web
    name: n8n
    env: docker
    region: oregon # Optional: Default to Oregon region
    plan: free  # Free plan for Render
    branch: main # Make sure you're deploying from the main branch
    numInstances: 1
    healthCheckPath: / # Render will check the root path to ensure n8n is healthy
    envVars:
      - key: PGHOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: PGDATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: PGPORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: PGUSER
        fromDatabase:
          name: n8n-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: WEBHOOK_URL
        value: https://<CHANGEME>.render.com/ # Replace with your actual URL after deployment
    disk:
      name: n8n-disk
      mountPath: /home/node/.n8n # Path where n8n stores its data
      sizeGB: 2

databases:
  - name: n8n-db
    plan: free-256mb # Use free 256MB PostgreSQL database
